// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WeebTracker.EntityFramework;

#nullable disable

namespace WeebTracker.EntityFramework.Migrations
{
    [DbContext(typeof(WeebTrackerDBContext))]
    [Migration("20250610184740_constructor")]
    partial class constructor
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Models.DBModels.Collectible", b =>
                {
                    b.Property<int>("CollectiblesID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CollectiblesID"));

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<bool>("Finalised")
                        .HasColumnType("bit");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Medium")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title_German")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title_Japanese")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CollectiblesID");

                    b.ToTable("Collectibles");

                    b.HasDiscriminator().HasValue("Collectible");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Models.DBModels.EditionInfo", b =>
                {
                    b.Property<int>("EditionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EditionID"));

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<int>("CollectiblesID")
                        .HasColumnType("int");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("nvarchar(21)");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<int>("Volume")
                        .HasColumnType("int");

                    b.HasKey("EditionID");

                    b.HasIndex("CollectiblesID");

                    b.ToTable("EditionInfos");

                    b.HasDiscriminator().HasValue("EditionInfo");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Models.DBModels.Anime", b =>
                {
                    b.HasBaseType("Models.DBModels.Collectible");

                    b.Property<int?>("CollectiblesTempId11")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Director")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasIndex("CollectiblesTempId11");

                    b.HasDiscriminator().HasValue("Anime");
                });

            modelBuilder.Entity("Models.DBModels.Manga", b =>
                {
                    b.HasBaseType("Models.DBModels.Collectible");

                    b.Property<string>("Autor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CollectiblesTempId2")
                        .HasColumnType("int");

                    b.HasIndex("CollectiblesTempId2");

                    b.HasDiscriminator().HasValue("Manga");
                });

            modelBuilder.Entity("Models.DBModels.AnimeEditionInfo", b =>
                {
                    b.HasBaseType("Models.DBModels.EditionInfo");

                    b.Property<int>("Endepisode")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Startepisode")
                        .HasColumnType("int");

                    b.Property<string>("StorageMedium")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("AnimeEditionInfo");
                });

            modelBuilder.Entity("Models.DBModels.MangaEditionInfo", b =>
                {
                    b.HasBaseType("Models.DBModels.EditionInfo");

                    b.Property<int>("EndChapter")
                        .HasColumnType("int");

                    b.Property<bool>("FirstEdition")
                        .HasColumnType("bit");

                    b.Property<int>("StartChapter")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("MangaEditionInfo");
                });

            modelBuilder.Entity("Models.DBModels.EditionInfo", b =>
                {
                    b.HasOne("Models.DBModels.Collectible", "Collectibles")
                        .WithMany("EditionInfo")
                        .HasForeignKey("CollectiblesID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Collectibles");
                });

            modelBuilder.Entity("Models.DBModels.Anime", b =>
                {
                    b.HasOne("Models.DBModels.Collectible", "Collectibles")
                        .WithMany()
                        .HasForeignKey("CollectiblesTempId11");

                    b.Navigation("Collectibles");
                });

            modelBuilder.Entity("Models.DBModels.Manga", b =>
                {
                    b.HasOne("Models.DBModels.Collectible", "Collectibles")
                        .WithMany()
                        .HasForeignKey("CollectiblesTempId2");

                    b.Navigation("Collectibles");
                });

            modelBuilder.Entity("Models.DBModels.Collectible", b =>
                {
                    b.Navigation("EditionInfo");
                });
#pragma warning restore 612, 618
        }
    }
}
